version: '3.8'

services:
  ambev.developerevaluation.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;User Id=developer;Password=ev@luAt10n;
      - ConnectionStrings__RedisConnection=ambev.developerevaluation.cache,6379,password=ev@luAt10n
      - ConnectionStrings__MongoConnection=mongodb://developer:ev%40luAt10n@ambev.developerevaluation.nosql:27017/?authSource=admin